### ISSUE TITLE
Correctly bill shipping for classics, contemporary and annual membership

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#102]
Classic, contemporary and annual plans bill in a strange way:

For classic/contemporary products
- Delivery is every two months
- But we want to charge monthly, spreading the shipping and membership fees evenly

For annual plans:
- Delivery is every month or two, depending on the product
- Shipping fees need to be paid up front for the year, in aggregate

Let's take annual plans first, as this is currently nonfunctional:
- We need to know how many deliveries are made per year, in order to calculate the shipping fee
- We could potentially use the `subscription.line_items.quantity` field for this purpose

For classic/contemporary products:
- Annual prices would include `metafields: { deliveries_per_year: 6 }`
- We cannot do a separate billing cycle for membership and shipping fees, so we'd have to halve the shipping rate somehow, so we'd probably do something like `metafields: { deliveries_per_year 6 }` on the price

### Options
1. Use metafields in Stripe to configure this
  - deliveries_per_year: 6
2. Define subscription pricing in Wagtail, like below. Then we'd generate one-off line items. We can calculate 
    ```yaml
      - deliveries_per_year = 6
      - prices:
          - price: 1 GBP
             interval = "month"
             interval_count = 2
          - price: 1 GBP
             interval = "year"
             interval_count = 1
      - product_options_label = "Choose a book series"
      - products:
         # If one, pick it.
         # If multiple, go to product pick page
         - product: "prod_classic"
            description: "..."
         - product: "prod_contemporary"
            description: "..."
    ```

Option 1 in a bit simpler. Option 2 might be more desirable as it becomes much much more explicit what prices will display and in what order / with what styling things will show up, which is a topic in #41. For example, if you pick '6 books a year', you can then pick the product. And we avoid having to make a weird grid of products and prices in the stripe dashboard to fulfill the desired display logic on the website.

### Plan

- [X] MembershipOptions MVP
  - [x] Switch between annual / monthly if possible
  - [x] Buy this as a gift
  - [ ] Style the membership plan page
- [X] MVP structblock
  - [x] Switch between annual / monthly if possible
  - [x] Buy this as a gift
  - [x] Style the structblock
- [X] If multiple products, route to the different product options with Product ID options
- [ ] Arrive at delivery view with price ID
  - [ ] Switch between annual / monthly
  - [ ] Generate line items
